# Default values for lustre-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  image: "ghcr.io/hewlettpackard/lustre-csi-driver"
  tag: "0.1.5"
