apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: lustre-fs
  persistentVolumeReclaimPolicy: Retain
  # Reserve this PV for the matching PVC.
  claimRef:
    kind: PersistentVolumeClaim
    name: pvc-example
    namespace: lustre-csi-system
  # Represent the volume as managed by an external CSI volume driver
  # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#csipersistentvolumesource-v1-core
  csi:
    # Driver is the name of the driver to use for this volume. Must match the CSIDriver's metadata.name found in driver.yaml.
    driver: lustre-csi.hpe.com
    # VolumeHandle is the unique volume name returned by the CSI volume plugin's CreateVolume to refer to
    # the volume on all subsequent calls. For Lustre, this is the NID list of the filesystem MGS, and may have varying
    # formats based on the networking interface type. Example formats:
    # - RoCE = <ip_addr>@tcp:/<fs_name>,
    # - Infiniband = <ip_addr>@o2ib:/<fs_name>
    volumeHandle: "172.0.0.1@tcp:/maui"
    # Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. "ext4", "xfs", "ntfs".
    fsType: lustre