apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lustre-csi-system

resources:
- namespace.yaml
- driver.yaml
- plugin.yaml

#patchesStrategicMerge:
#- plugin_imagepullsecret_patch.yaml

images:
- name: controller
  newName: ghcr.io/hewlettpackard/lustre-csi-driver
  newTag: 0.1.2
