apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lustre-csi-system
resources:
  - namespace.yaml
  - driver.yaml
  - plugin.yaml
images:
  - name: controller
  - newName: ghcr.io/hewlettpackard/lustre-csi-driver
  - newTag: 5fa68458cbcd53aa0b61749b4f7f8cd99401b814