apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  # This name must match the name of the CSI SP, found in service/service.go.
  # Then any PV may reference this in its own spec.csi.driver.
  name: lustre-csi.hpe.com
  namespace: lustre-csi-system
  labels:
    app.kubernetes.io/instance: lustre-csi.hpe.com
    app.kubernetes.io/part-of: lustre-csi-driver
    app.kubernetes.io/name: lustre-csi.hpe.com
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/version: {{ .Values.deployment.tag }}
spec:
  # Indicates this CSI volume driver requires an attachment operation because it implements the CSI
  # ControllerPublishVolume() method, and that the Kubernetes attach/detach controller should call
  # the attachment volume interface (which checks the volumeAttach status) and waits until the volume
  # is attached before proceeding to mounting.
  attachRequired: false

  # Indicates this CSI volume driver requires additional pod information (i.e. PodName, PodUID, etc.)
  # during mount operations. This CSI driver specifies podInfoOnMount as part of driver deployment.
  # If true, Kubelet will pass pod information as VolumeContext in the CSI NodePublishVolume() calls.
  # The CSI driver is responsible for parsing and validating the information passed as VolumeContext.
  # The following information is presented, with a common prefix:
  #    "csi.storage.k8s.io/pod.name": pod.Name
  #    "csi.storage.k8s.io/pod.namespace": pod.Namespace
  #    "csi.storage.k8s.io/pod.uid": string(pod.UID)
  #    "csi.storage.k8s.io/ephemeral": "true" (or "false")
  podInfoOnMount: false
