namePrefix: mock-
bases:
  - ../base
patchesJSON6902:
  - target:
      version: v1
      kind: PersistentVolume
      name: pv-example
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: mock-sc-example
      - op: replace
        path: /spec/csi
        value:
          # Driver is the name of the driver to use for this volume
          driver: mock-csi.nnf.cray.hpe.com
          volumeHandle: f58bff9c-e0d6-46bd-a51d-4457dd921fda
          fsType: mock

  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: pvc-example
    patch: |-
        - op: replace
          path: /spec/storageClassName
          value: mock-sc-example
        - op: replace
          path: /spec/volumeName
          value: mock-pv-example
  
  - target:
      version: v1
      group: storage.k8s.io
      kind: StorageClass
      name: sc-example
    patch: |-
      - op: replace
        path: /provisioner
        value: mock-csi.nnf.cray.hpe.com

  - target:
      version: v1
      kind: Pod
      name: app-example
    patch: |-
      - op: replace
        path: /spec/volumes/0/persistentVolumeClaim/claimName
        value: mock-pvc-example

  