kind: Pod
apiVersion: v1
metadata:
  name: app-example
  namespace: lustre-bluster
spec:
  containers:
  - name: busybox
    image: busybox
    command: [ "sleep", "100000000" ]
    volumeMounts:
      - name: lustre-volume
        mountPath: /mnt/lus
  volumes:
    - name: lustre-volume
      persistentVolumeClaim:
        claimName: pvc-example # defined in pvc.yaml
