apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lustre-csi-node
spec:
  template:
    spec:
      containers:
      - name: csi-node-driver
        volumeMounts:
          - mountPath: /mnt
            name: mnt-dir
            mountPropagation: Bidirectional
          - mountPath: /dev
            name: dev-dir
            mountPropagation: HostToContainer
      volumes:
        - name: mnt-dir
          hostPath:
            path: /mnt
        - name: dev-dir
          hostPath:
            path: /dev
