---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurelustre
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  storageClassName: sc.azurelustre.csi.azure.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: deployment-azurelustre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: deployment-azurelustre
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: deployment-azurelustre
          image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
          command:
            - "/bin/sh"
            - "-c"
            - while true; do echo $(date) > /mnt/azurelustre/example_out_file; sleep 1; cat /mnt/azurelustre/example_out_file; sleep 5; done
          volumeMounts:
            - name: azurelustre
              mountPath: "/mnt/azurelustre"
              readOnly: false
      volumes:
        - name: azurelustre
          persistentVolumeClaim:
            claimName: pvc-azurelustre
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
