namePrefix: lustre-
bases:
  - ../base
patchesJSON6902:
  - target:
      version: v1
      kind: PersistentVolume
      name: pv-example
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: lustre-sc-example
      - op: replace
        path: /spec/csi
        value:
          # Driver is the name of the driver to use for this volume
          driver: lustre-csi.nnf.cray.hpe.com
          volumeHandle: "127.0.0.1@tcp:/maui"
          fsType: lustre

  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: pvc-example
    patch: |-
        - op: replace
          path: /spec/storageClassName
          value: lustre-sc-example
        - op: replace
          path: /spec/volumeName
          value: lustre-pv-example
  
  - target:
      version: v1
      group: storage.k8s.io
      kind: StorageClass
      name: sc-example
    patch: |-
      - op: replace
        path: /provisioner
        value: lustre-csi.nnf.cray.hpe.com

  - target:
      version: v1
      kind: Pod
      name: app-example
    patch: |-
      - op: replace
        path: /spec/volumes/0/persistentVolumeClaim/claimName
        value: lustre-pvc-example

  