apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: lustre-csi-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: plugin
    app.kubernetes.io/instance: lustre-csi.hpe.com
    app.kubernetes.io/name: lustre-csi-node
    app.kubernetes.io/part-of: lustre-csi-driver
  name: lustre-csi-node
  namespace: lustre-csi-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: plugin
      app.kubernetes.io/instance: lustre-csi.hpe.com
      app.kubernetes.io/name: lustre-csi-node
      app.kubernetes.io/part-of: lustre-csi-driver
  template:
    metadata:
      labels:
        app.kubernetes.io/component: plugin
        app.kubernetes.io/instance: lustre-csi.hpe.com
        app.kubernetes.io/name: lustre-csi-node
        app.kubernetes.io/part-of: lustre-csi-driver
    spec:
      containers:
      - args:
        - --driver=mock
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: X_CSI_DEBUG
          value: "true"
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: ghcr.io/hewlettpackard/lustre-csi-driver:latest
        name: csi-node-driver
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
        - mountPath: /var/lib/kubelet/plugins
          mountPropagation: Bidirectional
          name: plugins-dir
        - mountPath: /dev
          mountPropagation: HostToContainer
          name: dev-dir
        - mountPath: /mnt
          mountPropagation: Bidirectional
          name: mnt-dir
      - args:
        - --v=5
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/$(CSI_DRIVER)/csi.sock
        env:
        - name: CSI_DRIVER
          value: lustre-csi
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.5.0
        name: csi-node-driver-registrar
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /registration
          name: registration-dir
      initContainers:
      - command:
        - sh
        - -c
        - rm -f /csi/csi.sock
        image: busybox:1.28
        name: init-socket
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/lustre-csi
          type: DirectoryOrCreate
        name: socket-dir
      - hostPath:
          path: /var/lib/kubelet/pods
          type: Directory
        name: mountpoint-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet/plugins
          type: Directory
        name: plugins-dir
      - hostPath:
          path: /dev
          type: Directory
        name: dev-dir
      - hostPath:
          path: /mnt
          type: Directory
        name: mnt-dir
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  labels:
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/instance: lustre-csi.hpe.com
    app.kubernetes.io/name: lustre-csi.hpe.com
    app.kubernetes.io/part-of: lustre-csi-driver
  name: lustre-csi.hpe.com
spec:
  attachRequired: false
  podInfoOnMount: false
