# Pushing a tag triggers this workflow, which verifies that it is an
# annotated tag.
name: Verify tag

on:
  push:
    tags:
      - "v*"

jobs:
  verify_tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Verify context"
        run: |
          echo "ref is ${{ github.ref }}"
          echo "ref_type is ${{ github.ref_type }}"

      - uses: actions/checkout@v3
        # actions/checkout@v3 breaks annotated tags by converting them into
        # lightweight tags, so we need to force fetch the tag again
        # See: https://github.com/actions/checkout/issues/290
      - name: "Repair tag"
        run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}
      - name: "Verify tag is annotated"
        run: if test x$(git for-each-ref ${{ github.ref }} | awk '{print $2}') = xtag; then /bin/true; else echo "\"${{ github.ref }}\" does not look like an annotated tag!"; /bin/false; fi
      - name: "Echo release tag"
        run: echo "TAG=${{ github.repository }}:${{ github.ref }}"
